**Machine Learning Detector for Malware**

*Signature Based Analysis*
This is effective for known malware, but not for new malware.It is also not effective for polymorphic malware. It is fast and efficient.

First, we will import the libraries we need for this project from ClaMP_Integrated-5184.csv. We will use the pandas library to read the csv file and the numpy library to convert the data into an array. We will only show a sample of the data. But working on the project will be done with the entire data.

In [7]:
import pandas as pd

data = pd.read_csv('ClaMP_Integrated-5184.csv')
data.head(20)

e_cblp  e_cp  e_cparhdr  e_maxalloc  e_sp  e_lfanew  NumberOfSections  \
0      144     3          4       65535   184       256                 4   
1      144     3          4       65535   184       184                 4   
2      144     3          4       65535   184       272                 5   
3      144     3          4       65535   184       184                 1   
4      144     3          4       65535   184       224                 5   
5       80     2          4       65535   184       256                 8   
6      144     3          4       65535   184       272                 8   
7      144     3          4       65535   184       256                 5   
8      144     3          4       65535   184       240                 5   
9      144     3          4       65535   184       224                 6   
10     144     3          4       65535   184       248                 4   
11     144     3          4       65535   184       128                 3   
12     144     3          4       65535   184       200                 3   
13     144     3          4       65535   184       272                 8   
14     144     3          4       65535   184       128                 3   
15     144     3          4       65535   184       240                 4   
16     144     3          4       65535   184       224                 5   
17     144     3          4       65535   184       248                 5   
18     144     3          4       65535   184       224                 3   
19     144     3          4       65535   184       200                 3   

    CreationYear  FH_char0  FH_char1  ...  sus_sections  non_sus_sections  \
0              1         0         1  ...             1                 3   
1              1         0         1  ...             1                 3   
2              1         0         1  ...             1                 4   
3              1         0         1  ...             0                 1   
4              1         0         1  ...             1                 4   
5              1         0         1  ...             4                 4   
6              1         0         1  ...             4                 4   
7              1         0         1  ...             1                 4   
8              1         0         1  ...             1                 4   
9              1         0         1  ...             1                 5   
10             1         0         1  ...             1                 3   
11             1         0         1  ...             1                 2   
12             1         1         1  ...             0                 3   
13             1         0         1  ...             3                 5   
14             1         0         1  ...             1                 2   
15             1         0         1  ...             1                 3   
16             1         0         1  ...             1                 4   
17             1         0         1  ...             1                 4   
18             1         1         1  ...             0                 3   
19             1         1         1  ...             0                 3   

    packer             packer_type    E_text    E_data  filesize    E_file  \
0        0                NoPacker  6.603616  5.443362   1181520  6.627552   
1        0                NoPacker  5.205926  2.123522      7680  5.318221   
2        0                NoPacker  6.238000  3.380859     57872  6.507758   
3        0                NoPacker  0.000000  0.000000     95616  4.575092   
4        0                NoPacker  6.355626  0.702621     48128  5.545531   
5        0                NoPacker  0.000000  0.000000  13411640  7.999277   
6        1       Armadillov1xxv2xx  6.595606  2.843601    397936  6.295515   
7        0                NoPacker  5.990481  1.425743     61968  5.766049   
8        0                NoPacker  6.019617  3.185497     54272  

*Data Preprocessing*
We will use the LabelEncoder class of the sklearn.preprocessing library to convert the data into an array. We will convert the data in the "sus_sections" column to 0, 1, 2 ,3 and 4. 0 means that the file is not malware and 1, 2, 3, 4 means that the file is malware it also shows the level effect.

In [8]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data["sus_sections"] = le.fit_transform(data["sus_sections"])
print(data["sus_sections"].head(20))


0     1
1     1
2     1
3     0
4     1
5     4
6     4
7     1
8     1
9     1
10    1
11    1
12    0
13    3
14    1
15    1
16    1
17    1
18    0
19    0
Name: sus_sections, dtype: int64


*Encode the data*
We will use the OneHotEncoder class of the sklearn.preprocessing library to convert the data into an array. We will convert the data in the "sus_sections" column to 0, 1, 2 ,3 and 4. 0 means that the file is not malware and 1, 2, 3, 4 means that the file is malware it also shows the level effect.

In [9]:
from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()
data = ohe.fit_transform(data).toarray()
print(data[0:20])

[[0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 ...
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 1. 1. 0.]]
